name = "GeometricUnits"
uuid = "43c95830-f66f-43f3-8298-be5f3865d5b9"
authors = ["Abhimanyu Susobhanan <abhisrkckl@gmail.com>"]
version = "0.1.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestExtras = "5ed8adda-3752-4e41-b88a-e8b09835ee3a"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "TestExtras", "JuliaFormatter", "Quadmath", "Zygote", "StaticArrays", "BenchmarkTools"]
